---

- name: Install collectd packages
apt: name=collectd state=present

- name: create collectd data folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
      - "{{ collectd_data_path }}"
      
- name: configure collectd
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf

- name: Enable collectd
  service: name=collectd enabled=yes
  notify:
    - Restart collectd
