---

- name: create meshviewer config
  template:
    src: config.js.j2
    dest: "{{ meshviewer_src }}/config.js"
    mode: 0644
    owner: root
    group: root
  become: false

- name: yarn meshviewer_dep
  command:
    args:
      executable: /usr/bin/yarn
      chdir: "{{ meshviewer_src }}"
    become: false

- name: building
  command: /usr/bin/yarn run gulp
  args:
    chdir: "{{ meshviewer_src }}"
    become: false

- name: deploy
  command: 'rm -rf {{ meshviewer_path }}/* && cp -ar build/* {{ meshviewer_path }} && chown www-data:www-data -R {{ meshviewer_path }}'
  args:
    executable: /bin/bash
    chdir: "{{ meshviewer_src }}"
    warn: no

- name: write vhost
  template:
    src: meshviewer_vhost.conf.j2
    dest: /etc/nginx/conf.d/meshviewer.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
